version: 2
orbs:
  node: circleci/node@4.7.0
jobs:
  node-12.4:
    docker:
      - image: circleci/node:latest-browsers
      - image: circleci/mongo:4.2
        environment:
          - DB_CONNECTION_STRING: "mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASSWORD}@cluster0.6zhup.mongodb.net/database?retryWrites=true&w=majority"
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: npm install
      - run: npm run test
      - run: npm run test_coverage

workflows:
  version: 2
  build:
    jobs:
      - node-12.4: 
          context: mongo
